### ISSUE TITLE
 from googlesearch import search  ImportError: cannot import name 'search'

### ISSUE THREAD

**Issue by nivedithapatil** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#15]
**Have you read [Troubleshooting.md](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/blob/master/docs/Troubleshooting.md)? If No, please do so before filing an issue.**
Yes/No

**Have you tried Googling the problem?**
Yes/No

**Which python version are you using to run the project? In the terminal, type ```which <python-path-you-have-in-clientServer.php>``` and enter the output here**
Python version -

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version (optional) [e.g. 22]

**Smartphone (please complete the following information):**
 - Version (optional) [e.g. 22]

**Additional context**

**Comment by rohitnaik246** [comment]
Hi, you need to fill up the template with answers related to your issue.
