### ISSUE TITLE
RE: Opening project in anaconda, Spyder, Juypter Notebook

### ISSUE THREAD

**Issue by Autodestruction** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#16]
Hello there, 

I am fairly new to python, and I was wondering how do you possibly open this project in either, anaconda spyder, Juypter Notebook (both are hosted locally on my system) and Pycharm? 

Also, as this project is done on Python 2.x, I assume this wont work on python 3.x? 

Thanks!

**Comment by philomathic-guy** [comment]
Hello,
Yes you can open it using Pycharm - Just open PyCharm > File > Open > Select the folder in which you cloned the project.
Yes, that is correct. There is a plan as of now to refactor the code to Python 3.x but as of now it will not work with Python 3.x

Closing the issue for now. Please reopen if you have more questions.
