### ISSUE TITLE
Where is the source of your data set? Can you give me the source of URL for the dataset?

### ISSUE THREAD

**Issue by angek44** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#17]
**Have you read [Troubleshooting.md](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/blob/master/docs/Troubleshooting.md)? If No, please do so before filing an issue.**
Yes/No

**Have you tried Googling about it?**
Yes/No

**Which python version are you using to run the project? In the terminal, type ```which <python-path-you-have-in-clientServer.php>``` and enter the output here**
Python version -

**Describe the question**
A clear and concise description of your question.

**Screenshots**
Add any screenshots, if necessary to describe your question better.

**Additional context**
Any additional information, if needed.

**Comment by philomathic-guy** [comment]
I do not have it handy.
