### ISSUE TITLE
 You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.

### ISSUE THREAD

**Issue by superoo1** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#18]
when load random_forest.pkl  , there is a problem :
 You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.

how to fix it?

**Comment by philomathic-guy** [comment]
The error is self explanatory. Read the exact message you are getting.
Opening issues is not a way to resolve simple issues. It is to report possible bugs, feature requests, improvements etc.
