### ISSUE TITLE
Errors while running project on windows 10, using python 2.7.16

### ISSUE THREAD

**Issue by Autodestruction** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#19]
**Have you read [Troubleshooting.md](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/blob/master/docs/Troubleshooting.md)? If No, please do so before filing an issue.**
Yes

**Have you tried Googling about it?**
Yes

**Which python version are you using to run the project? In the terminal, type ```which <python-path-you-have-in-clientServer.php>``` and enter the output here**
Python version - 2.7.16

**Describe the question**
A clear and concise description of your question.

**Screenshots**
![data_validation](https://user-images.githubusercontent.com/51444140/59857327-9e1f9180-9370-11e9-9328-ea6c909b77b3.PNG)

This is the error im getting when i run data_validation.py on pycharm. Do i need to change the directory accordingly to where it is placed in my folder that i pulled from your github? 

![test](https://user-images.githubusercontent.com/51444140/59857399-c7402200-9370-11e9-8427-ae02811fafd8.PNG)

the 2nd error i got is on test.py - it is stating that the list index is out of range, and im not really sure whats the problem since i havent changed anything from your project for amendments. 

![train1](https://user-images.githubusercontent.com/51444140/59857459-ec349500-9370-11e9-9c0e-94e7d78515c6.PNG)

3rd error is - on train.py where it states too many indices for array, once again i have not done any amendments from your project but just tried to run it on pycharm 

![chrome error](https://user-images.githubusercontent.com/51444140/59857523-053d4600-9371-11e9-867c-f844341f8000.PNG)

lastly, when i did host it on xampp and tried to run it on google chrome extension, i kept getting this issue (failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in <b>D:\XAMPP\htdocs\Malicious-Web-Content-Detection-Using-Machine-Learning\clientServer.php</b> on line <b>4</b><br /> operable program or batch file) 

Please any advice on this will be greatly appreciated. Thanks!

**Additional context**
Any additional information, if needed.

**Comment by philomathic-guy** [comment]
Hi,
The first error you are getting is just a path change. The path to the training dataset is now - 'dataset/Training Dataset.arff'. I have updated this in the recent-most commit.

Each file has an isolated purpose but is not meant to be run separately. If you want to run the code from the command line, without having to run the Chrome extension, please see the last few lines of features_extraction.py. There is a comment which explains how it is to be run. Try to connect those comments and the calls that are being made from there. Once you understand the flow of the code, you'll understand how it is operating.

Once again, you do not need to run each file separately. Try to understand the purpose of each file and see if it is needed to be run.

For the fourth issue, can you please uncomment Line 14 of Extension/popup.js, re-run the application and paste the detailed error description?

**Comment by Autodestruction** [comment]
Hi there, 

Thank you for your feedback, I will get back to you soon regarding the last error in abit.

**Comment by Autodestruction** [comment]
Hello there, as requested i will paste the error on the 4th issue here, please have a look

![error](https://user-images.githubusercontent.com/51444140/60169101-f685e180-97fd-11e9-8612-3ac6fd012c50.PNG)

2nd here on a different website below: 

![error1](https://user-images.githubusercontent.com/51444140/60169113-01407680-97fe-11e9-839d-eeda727fbd8d.PNG)

**Comment by philomathic-guy** [comment]
Have you tried Googling about the issue?
What were your findings?

**Comment by Autodestruction** [comment]
Hello there, 
Indeed i have looked on google for this issue, most of the replies were leaning towards google not giving permission to do such a service as its against their TOS or it was an issue with the API v2 & 3. I will post the findings as screenshots together with this so you might have a better understanding. 

Thanks
![problem](https://user-images.githubusercontent.com/51444140/60382054-6fcb4180-9a55-11e9-97a7-f709c198b52f.PNG)
![problem2](https://user-images.githubusercontent.com/51444140/60382055-7063d800-9a55-11e9-9cf4-014b3c4648be.PNG)

**Comment by Autodestruction** [comment]
Hi there, 

Just a follow up to the issue above, is it necessary for me to set a host path variable on my system in the first place as a requirement to run this project? I have tried every other possibilty but when it comes to running the chrome extension the same problem persist "operable program or batch file"

**Comment by philomathic-guy** [comment]
Hi,
This seems to be a system specific issue (Windows to be precise).
According to my own searching, I have a couple of observations - 
1. The error that you are seeing is a part of the complete error. Only the second part is getting printed because there is a return '\n' character in between the error. You should try to see the complete error to know which program file is not getting accessed.
2. Then you should add it to the path variables (since it looks like you have not used that particular program before).
Source - https://stackoverflow.com/questions/31291317/php-is-not-recognized-as-an-internal-or-external-command-in-command-prompt
