### ISSUE TITLE
Unable to load manifest

### ISSUE THREAD

**Issue by Magarajeswari** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#20]

**Comment by Magarajeswari** [comment]
![image](https://user-images.githubusercontent.com/52660002/60806963-08726780-a1a2-11e9-8b92-fc24b67ad55a.png)
I am getting an error as unable to read or load the manifest file.

**Comment by philomathic-guy** [comment]
Please fill up the template for filing issues.

Thanks!
