### ISSUE TITLE
issues in the chrome extension

### ISSUE THREAD

**Issue by bhavya998** [philomathic-guy/Malicious-Web-Content-Detection-Using-Machine-Learning#21]
**Have you read [Troubleshooting.md](https://github.com/rohitnaik246/Malicious-Web-Content-Detection-Using-Machine-Learning/blob/master/docs/Troubleshooting.md)? If No, please do so before filing an issue.**
Yes

**Have you tried Googling about it?**
Yes

**Which python version are you using to run the project? In the terminal, type ```which <python-path-you-have-in-clientServer.php>``` and enter the output here**

$decision=exec("C:/Python27 test.py $site 2>&1 ");

Python version - python 2.7.13

**Describe the question**
error 1
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience" is the error shown in the chrome extension settings

![er1](https://user-images.githubusercontent.com/53378883/61998161-5c011280-b0c9-11e9-8b5a-0406b881c1b5.PNG)

![er2](https://user-images.githubusercontent.com/53378883/61998164-63282080-b0c9-11e9-8e7c-c98183a17ea5.PNG)

the below mentioned is the line from the extension/popup.js which is at number 14
`xhr.open("POST","http://localhost/Malicious-Web-Content-Detection-Using-Machine-Learning/clientServer.php",false);`

error 2
in the extension itself below safe or not it shows error as follows
`<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <head> <title>Object not found!</title> <link rev="made" href="mailto:postmaster@localhost" /> <style type="text/css"><![CDATA[/*></style> </head> <body> <h1>Object not found!</h1> <p> The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again. </p> <p> If you think this is a server error, please contact the <a href="mailto:postmaster@localhost">webmaster</a>. </p> <h2>Error 404</h2> <address> <a href="/">localhost</a><br /> <span>Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/5.6.38</span> </address> </body> </html>  
`
![er3](https://user-images.githubusercontent.com/53378883/61998200-2f012f80-b0ca-11e9-99e7-c70fa439a04d.PNG)

![er4](https://user-images.githubusercontent.com/53378883/61998201-34f71080-b0ca-11e9-91c0-cb1fc9127efb.PNG)

**Additional context**
Thank you for the amazing work sir ! please help me to solve this problem.

**Comment by philomathic-guy** [comment]
Hi Bhavya,
Did you try looking for this issue in the previously filed issues?
Did you try doing a web search on the same?
I would really appreciate if you would post your answers about the above searches.

**Comment by bhavya998** [comment]
hello sir!
 
`xhr.open("POST","http://localhost/Malicious-Web-Content-Detection-Using-Machine-Learning/clientServer.php",false);
`
i changed the above coed to :
`xhr.open("POST","http://localhost/Malicious-Web-Content-Detection-Using-Machine-Learning/clientServer.php",true);`

but now the issue is,
 
![er1](https://user-images.githubusercontent.com/53378883/62082824-213ade00-b273-11e9-98d2-615b37542191.PNG)

that safe or not is just giving this dialog box / it is not taking the input 
it dosent shows any error so id ont whats wrong with it !

THANK YOU SO MUCH FOR YOUR REPLY SIR!

**Comment by bhavya998** [comment]
@philomathic-guy  please sir if u can give advice to solve the above issues it would be great ! thankyou
